# Generated by Django 4.2.7 on 2023-12-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
