# Generated by Django 4.2.7 on 2024-01-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'API.REGISTER.DUPLICATED'}, max_length=254, unique=True),
        ),
    ]
