# Generated by Django 4.2.7 on 2024-01-15 20:46

import audio_generator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path_audio', models.FileField(upload_to=audio_generator.models.Page.user_upload_to)),
                ('path_pdf', models.FileField(upload_to=audio_generator.models.Page.user_upload_to)),
                ('page_num', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='audio_generator.file')),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
