# Generated by Django 4.2.7 on 2023-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0002_remove_user_is_staff_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
