# Generated by Django 4.2.7 on 2024-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0004_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.IntegerField(choices=[(0, 'Uploading'), (1, 'Splitting'), (2, 'Generating'), (3, 'Completed')], default=0),
        ),
    ]
