# Generated by Django 4.2.7 on 2024-01-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0005_alter_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='working_processes',
            field=models.IntegerField(default=0),
        ),
    ]
