# Generated by Django 4.2.7 on 2024-02-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0006_file_working_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pages_num',
            field=models.IntegerField(default=0),
        ),
    ]
