# Generated by Django 4.2.7 on 2024-02-21 15:41

import audio_generator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0007_file_pages_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(max_length=500, upload_to=audio_generator.models.File.user_upload_to),
        ),
        migrations.AlterField(
            model_name='page',
            name='path_audio',
            field=models.FileField(max_length=500, upload_to=audio_generator.models.Page.user_upload_to),
        ),
        migrations.AlterField(
            model_name='page',
            name='path_pdf',
            field=models.FileField(max_length=500, upload_to=audio_generator.models.Page.user_upload_to),
        ),
    ]
