# Generated by Django 4.2.7 on 2024-02-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0009_remove_file_working_processes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='status',
        ),
    ]
