# Generated by Django 4.2.7 on 2024-02-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0010_remove_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lang',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
