# Generated by Django 4.2.7 on 2024-02-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0011_file_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pages_generated',
            field=models.BooleanField(default=False),
        ),
    ]
