# Generated by Django 4.2.7 on 2024-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_generator', '0012_file_pages_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(),
        ),
    ]
